Added better module feedback, adapter cutting, prepared keep-deletion option just in case it is needed.

diff --git a/IRMA b/IRMA
--- a/IRMA
+++ b/IRMA
@@ -30,6 +30,26 @@ else
 	exit 1
 fi
 
+#### UTILITY FUNCTIONS ####
+# FNC - ERROR TEST #
+# Idea courtesy: steve-parker.org/sh/exitcodes.shtml
+function err_test() {
+	if [ "$1" -ne "0" ];then
+		echo ""
+		if [ $# -eq "1" ]; then 
+			echo "$(basename $0) ERROR: operations have been ABORTED!"
+		else
+			echo "$(basename $0) ERROR ($2): operations have been ABORTED!"
+		fi
+		exit 1
+	fi
+}
+
+function time_stamp() {
+	local t=$(date +"%Y-%m-%d %k:%M:%S")
+	echo -e "[$t]\tIRMA/$MODULE $1"
+}
+###########################
 
 # variables
 OS="Linux"
@@ -89,7 +109,7 @@ fi
 # check for module
 MODULE2=$(echo $MODULE|cut -f1 -d'-')
 if [ ! -d $rpath/modules/$MODULE2 ];then
-	time_stamp "Error: $MODULE2 not found."
+	echo "IRMA ERROR: $MODULE2 not found."
 	exit 1
 else
 	mpath=$rpath/modules/$MODULE2	
@@ -122,7 +142,16 @@ fi
 
 # init variables from config files
 [ -r $mpath/init.sh ] && source $mpath/init.sh
-source $mpath/config/$MODULE.sh
+
+if [ -r "$mpath/config/$MODULE.sh" ];then
+	source $mpath/config/$MODULE.sh
+else
+	echo "IRMA ERROR: Configuration '$MODULE' not found. Valid configs are:"
+	tmp=" "
+	for i in $mpath/config/*sh;do tmp="$tmp $(basename $i .sh)";done
+	echo $tmp
+	exit 0
+fi
 REF1_SET=$REF_SET
 
 # check for profiles
@@ -187,28 +216,7 @@ BLAT_OPTS="-oneOff=1 -minIdentity=80 -tileSize=10"
 
 # FASTQ converter/QC options
 FASTQ_CONV_OPTS="-Q -M -T $QUAL_THRESHOLD -L $MIN_LEN"
-
-
-#### FUNCTIONS ####
-
-# FNC - ERROR TEST #
-# Idea courtesy: steve-parker.org/sh/exitcodes.shtml
-function err_test() {
-	if [ "$1" -ne "0" ];then
-		echo ""
-		if [ $# -eq "1" ]; then 
-			echo "$(basename $0) ERROR: operations have been ABORTED!"
-		else
-			echo "$(basename $0) ERROR ($2): operations have been ABORTED!"
-		fi
-		exit 1
-	fi
-}
-
-function time_stamp() {
-	local t=$(date +"%Y-%m-%d %k:%M:%S")
-	echo -e "[$t]\tIRMA/$MODULE $1"
-}
+[ "$PAIRED" -eq "1" -a "$ADAPTER" != "" ] && FASTQ_CONV_OPTS="$FASTQ_CONV_OPTS -c $ADAPTER"
 
 
 #####################
@@ -505,6 +513,7 @@ function doALIGN() {
 	time_stamp "$prefix rough aligned reads using $ALIGN_PROG"
 
 	# CREATE NEW REFERENCES
+	local PREV=$(expr $R - 1)
 	if [ "$ALIGN_PROG" != "NONE" ];then
 		for i in $sortp/$prefix-*.fa;do
 			name=$(basename $i .fa)
@@ -528,12 +537,6 @@ function doRound() {
 	local name=""
 
 	time_stamp "$prefix started ($n)"
-
-	# make sure directories are available
-	[ ! -d $ppath/MATCH ] && mkdir $ppath/MATCH
-	[ ! -d $ppath/SORT ] && mkdir $ppath/SORT
-	[ ! -d $ppath/ALIGN ] && mkdir $ppath/ALIGN
-	[ ! -d $ppath/GENES ] && mkdir $ppath/GENES
 
 	# MATCH stage
 	doMATCH $DB $prefix
@@ -575,6 +578,15 @@ function doRound() {
 			test -n "$(shopt -s nullglob;echo $sortp/R*-${gene}.fa)" && mv $i $sortp/$(basename $i .2)
 		done
 	fi
+
+	if [ "$ASSEM_REF" -eq "0" -a "$R" -eq "1" ];then
+		if test -n "$(shopt -s nullglob;echo $sortp/$prefix-*.fa)";then
+			name=$(basename $i .fa)
+                        gene=${name#*-}
+			$Lspath/selectSequences.pl -I $gene $REF1_SET > $refp/R0-${gene}.ref
+		fi
+	fi
+	
 
 	### ALIGN stage ###
 	# given we have primary data in this around	
@@ -818,6 +830,7 @@ function REFINE_ASSEMBLY_CALL_PHASE() {
 	rm $assemp/${gene}_????.fastq
 	rm $assemp/*-${gene}-????.*
 	rm $assemp/*-${gene}.sh
+	return $iter
 }
 
 function ASSEMBLE_REPORT() {
@@ -827,6 +840,7 @@ function ASSEMBLE_REPORT() {
 	local size=$(expr $(wc -l < $fastq) / 4)
 	local doGrid=0
 	local procs=0
+	local last_iter=1
 
 	# SCOPE
 	if [ "$size" -gt "$LIMIT_SSW" -a "$GRID_ON" -eq "1" ];then
@@ -849,7 +863,8 @@ function ASSEMBLE_REPORT() {
 	fi
 	time_stamp "started $gene ($size)"
 	REFINE_ASSEMBLY_CALL_PHASE $gene $procs $doGrid $final
-	
+	last_iter=$?	
+
 	local n=$(wc -l < ${final}-variants.txt)
 	if [ $n -gt 2 ]; then
 		$PARALLEL $RSCRIPT $spath/sqmHeatmap.R ${final}-{}.sqm ${final}-{}.pdf 2 ::: EXPENRD JACCARD MUTUALD NJOINTP > /dev/null
@@ -871,7 +886,7 @@ function ASSEMBLE_REPORT() {
 	$SAMTOOLS sort ${final}.bam $final > /dev/null 2>&1
 	$SAMTOOLS index ${final}.bam > /dev/null 2>&1
 	rm $assemp/F*-$gene.sam
-	time_stamp "finished $gene"
+	time_stamp "finished $gene (F$last_iter)"
 }
 
 function doPostProcessing() {
